language: node_js
os:
  - linux
node_js:
  - "4"
  - "5.6.0"
  - "5"  # Introduced "cachedData"/"produceCachedData" after 5.7, need 5.10 for Buffer.from()
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
  - "15"
script:
  - case "$TRAVIS_NODE_VERSION" in
    4|5.6.0|5)
      tap test/node-version-test.js
      ;;
    *)
      npm run test
      npm run lint
      npm run bench
      ;;
    esac
